import { Inter } from "next/font/google";
import "./globals.css";

import TransitionProvider from "@/components/TransitionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} w-[100%] min-h-screen bg-gradient-to-b from-blue-50 to-red-100`}
      >
        <TransitionProvider>{children}</TransitionProvider>
      </body>
    </html>
  );
}
